version: '3.8'

services:
  book-management-app:
    image: book-management-app:latest
    ports:
      - "1323:1323"
    environment:
      PORT: 1323
      DATABASE_DSN: "springstudent:springstudent@tcp(mysql:3306)/book_db?charset=utf8mb4&parseTime=True&loc=Local"
    container_name: book-management-app-container
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: book_db
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "6033:3306"
    container_name: mysql-db
